services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: freeleirix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:

